version: '2'
services:
  api:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./:/app  
    restart: always
  database:
    image: mongo
    ports:
      - "27017:27017"